-- Test fixture for identity columns
-- Covers: GENERATED ALWAYS AS IDENTITY, GENERATED BY DEFAULT AS IDENTITY, and options

CREATE TABLE identity_test (
    id_always bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    id_default bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_options integer GENERATED ALWAYS AS IDENTITY (START WITH 100 INCREMENT BY 10) NOT NULL,
    val text
);

ALTER TABLE ONLY identity_test ADD CONSTRAINT identity_test_pkey PRIMARY KEY (id_always);
