-- Test fixture for identity columns
-- Covers: GENERATED ALWAYS AS IDENTITY, GENERATED BY DEFAULT AS IDENTITY

CREATE TABLE public.users (
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    email text NOT NULL,
    name text NOT NULL
);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);

CREATE TABLE public.orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id bigint NOT NULL,
    total numeric(10,2) NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT NOW()
);

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);

CREATE TABLE public.products (
    id integer GENERATED ALWAYS AS IDENTITY (START WITH 100 INCREMENT BY 10) NOT NULL,
    name text NOT NULL,
    price numeric(10,2) NOT NULL
);

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);

CREATE TABLE public.logs (
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    message text NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT NOW()
);

ALTER TABLE ONLY public.logs
    ADD CONSTRAINT logs_pkey PRIMARY KEY (id);
