CREATE SEQUENCE shared_seq START WITH 1 INCREMENT BY 1 NO MAXVALUE CACHE 1;

CREATE SEQUENCE complex_seq
    START WITH 1000
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 999999999
    CACHE 10;

CREATE SEQUENCE cycle_seq
    START WITH 1
    INCREMENT BY 1
    CACHE 5
    CYCLE;

CREATE TABLE shared_table_1 (
    id bigint  DEFAULT nextval('shared_seq'::regclass) PRIMARY KEY
);

CREATE TABLE shared_table_2 (
    id bigint  DEFAULT nextval('shared_seq'::regclass) PRIMARY KEY
);

CREATE TABLE serial_types (
    id_big BIGSERIAL PRIMARY KEY,
    id_reg SERIAL,
    id_small SMALLSERIAL
);

CREATE TABLE identity_test (
    id_always bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_default bigint GENERATED BY DEFAULT AS IDENTITY,
    id_options integer GENERATED ALWAYS AS IDENTITY (START WITH 100 INCREMENT BY 10)
);

CREATE TABLE complex_seq_table (
    id bigint NOT NULL DEFAULT nextval('complex_seq'::regclass) PRIMARY KEY
);

CREATE TABLE cycle_table (
    id bigint NOT NULL DEFAULT nextval('cycle_seq'::regclass) PRIMARY KEY
);

ALTER SEQUENCE complex_seq RESTART WITH 2000;

ALTER SEQUENCE cycle_seq INCREMENT BY 2;
