-- Test fixture for identity and sequences
-- Transformations tested:
--   - Dedicated sequence → BIGSERIAL/SERIAL/SMALLSERIAL conversion
--   - Shared sequence → preserved (not converted)
--   - Identity columns (GENERATED ALWAYS/BY DEFAULT)
--   - Sequence options (START WITH, CACHE, CYCLE, etc.)
--   - nextval normalization

-- ============================================
-- 1. Shared sequence (preserved)
-- ============================================
CREATE SEQUENCE shared_seq START WITH 1 INCREMENT BY 1 NO MAXVALUE CACHE 1;

CREATE TABLE shared_table_1 (
    id bigint NOT NULL DEFAULT nextval('shared_seq'::regclass)
);
ALTER TABLE ONLY shared_table_1 ADD PRIMARY KEY (id);

CREATE TABLE shared_table_2 (
    id bigint NOT NULL DEFAULT nextval('shared_seq'::regclass)
);
ALTER TABLE ONLY shared_table_2 ADD PRIMARY KEY (id);

-- ============================================
-- 2. Dedicated sequences (convert to SERIAL)
-- ============================================
CREATE TABLE serial_types (
    id_big bigint NOT NULL,
    id_reg integer NOT NULL,
    id_small smallint NOT NULL
);
ALTER TABLE ONLY serial_types ADD PRIMARY KEY (id_big);

CREATE SEQUENCE seq_big OWNED BY serial_types.id_big;
CREATE SEQUENCE seq_reg OWNED BY serial_types.id_reg;
CREATE SEQUENCE seq_small OWNED BY serial_types.id_small;

ALTER TABLE serial_types ALTER COLUMN id_big SET DEFAULT nextval('seq_big');
ALTER TABLE serial_types ALTER COLUMN id_reg SET DEFAULT nextval('seq_reg');
ALTER TABLE serial_types ALTER COLUMN id_small SET DEFAULT nextval('seq_small');

-- ============================================
-- 3. Identity Columns
-- ============================================
CREATE TABLE identity_test (
    id_always bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_default bigint GENERATED BY DEFAULT AS IDENTITY,
    id_options integer GENERATED ALWAYS AS IDENTITY (START WITH 100 INCREMENT BY 10)
);

-- ============================================
-- 4. Sequence Options & ALTER SEQUENCE
-- ============================================
CREATE SEQUENCE complex_seq
    START WITH 1000
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 999999999
    CACHE 10;

CREATE TABLE complex_seq_table (
    id bigint NOT NULL DEFAULT nextval('complex_seq'::regclass) PRIMARY KEY
);

ALTER SEQUENCE complex_seq RESTART WITH 2000;

-- Sequence with CYCLE
CREATE SEQUENCE cycle_seq
    START WITH 1
    INCREMENT BY 1
    CACHE 5
    CYCLE;

CREATE TABLE cycle_table (
    id bigint NOT NULL DEFAULT nextval('cycle_seq'::regclass) PRIMARY KEY
);

ALTER SEQUENCE cycle_seq INCREMENT BY 2;
